- name: Create a new database
  postgresql_db: name={{ gitlab_db_name }}
                 encoding='UTF-8'
                 owner={{ db_user }}
                 template='template0'
                 login_user=postgres
  become_user: postgres

- name: Create an extension pg_trgm
  postgresql_ext: name=pg_trgm
                  db={{ gitlab_db_name }}
                  login_user=postgres
  become_user: postgres

- name: Configure the database settings
  lineinfile: dest=/etc/gitlab/gitlab.rb
              backrefs=yes
              regexp={{ item.regexp }}
              line={{ item.line }}
  with_items:
    - regexp: ^# postgresql\['enable'\]
      line:   "postgresql['enable'] = false"

    - regexp: ^# gitlab_rails\['db_adapter'\]
      line:   "gitlab_rails['db_adapter'] = \"postgresql\""

    - regexp: ^# gitlab_rails\['db_encoding'\]
      line:   "gitlab_rails['db_encoding'] = \"utf8\""

    - regexp: ^# gitlab_rails\['db_database'\]
      line:   "gitlab_rails['db_database'] = \"{{ gitlab_db_name }}\""

    - regexp: ^# gitlab_rails\['db_host'\]
      line:   "gitlab_rails['db_host'] = \"{{ db_host }}\""

    - regexp: ^# gitlab_rails\['db_port'\]
      line:   "gitlab_rails['db_port'] = 5432"

    - regexp: ^# gitlab_rails\['db_username'\]
      line:   "gitlab_rails['db_username'] = \"{{ db_user }}\""

    - regexp: ^# gitlab_rails\['db_password'\]
      line:   "gitlab_rails['db_password'] = \"{{ db_password }}\""
