- name: Install the necessary dependencies
  apt: pkg={{ item }} force=yes
  with_items:
    - curl
    - openssh-server
    - ca-certificates
    - postfix
  environment: "{{ proxy_env }}"

- name: Downlad and execute the script
  shell: curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash
  environment: "{{ proxy_env }}"

- name: Install GitLab
  apt: pkg=gitlab-ce force=yes
  environment: "{{ proxy_env }}"

- name: Backup gitlab.rb
  copy: src=/etc/gitlab/gitlab.rb
        dest=/etc/gitlab.rb.bk
        backup=yes
        owner=root
        group=root
        mode=0644

- include: db.yml

- name: Configure GitLab
  command: gitlab-ctl reconfigure

- name: Import default data
  command: env force=yes gitlab-rake gitlab:setup
