- name: Install the necessary dependencies
  apt: pkg={{ item }} force=yes
  with_items:
    - curl
    - openssh-server
    - ca-certificates
    - postfix
  environment: "{{ proxy_env }}"

- name: Download the GitLab script
  get_url: url=https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
           dest=/tmp/gitlab.script.sh
  environment: "{{ proxy_env }}"

- name: Execute the GitLab script
  shell: bash /tmp/gitlab.script.sh
  environment: "{{ proxy_env }}"

- name: Install GitLab
  apt: pkg=gitlab-ce force=yes
  environment: "{{ proxy_env }}"

- name: Backup /etc/gitlab/gitlab.rb
  shell: cp /etc/gitlab/gitlab.rb /etc/gitlab/gitlab.rb.bk
  args:
    creates: /etc/gitlab/gitlab.rb.bk

- include: database.yml

- include: web.yml

- name: Configure GitLab
  shell: gitlab-ctl reconfigure

# NOTE: This task INITIALIZES GitLab data
- name: Import default data
  shell: env force=yes gitlab-rake gitlab:setup
