- name: Install the necessary dependencies
  apt: pkg={{ item }} force=yes
  with_items:
    - curl
    - openssh-server
    - ca-certificates
    - postfix
  environment: "{{ proxy_env }}"

- name: Downlad and execute the script
  shell: curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash
  environment: "{{ proxy_env }}"

- name: Install GitLab
  apt: pkg=gitlab-ce force=yes
  environment: "{{ proxy_env }}"

- name: Backup /etc/gitlab/gitlab.rb
  shell: cp /etc/gitlab/gitlab.rb /etc/gitlab/gitlab.rb.bk
  args:
    creates: /etc/gitlab/gitlab.rb.bk

- include: db.yml

- name: Configure GitLab
  command: gitlab-ctl reconfigure

- name: Import default data
  command: env force=yes gitlab-rake gitlab:setup
