- name: Install the necessary dependencies
  apt: pkg={{ item }} force=yes
  with_items:
    - curl
    - openssh-server
    - ca-certificates
    - postfix
  environment: "{{ proxy_env }}"

- name: Download the GitLab script
  get_url: url=https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
           dest=/tmp/gitlab.script.sh
  environment: "{{ proxy_env }}"

- name: Execute the GitLab script
  command: bash /tmp/gitlab.script.sh
  environment: "{{ proxy_env }}"

- name: Install GitLab
  apt: pkg=gitlab-ce force=yes
  environment: "{{ proxy_env }}"

- name: Backup /etc/gitlab/gitlab.rb
  shell: cp /etc/gitlab/gitlab.rb /etc/gitlab/gitlab.rb.bk
  args:
    creates: /etc/gitlab/gitlab.rb.bk

- include: database.yml

- name: Configure the Gitlab settings
  lineinfile: dest=/etc/gitlab/gitlab.rb
              backrefs=yes
              regexp={{ item.regexp }}
              line={{ item.line }}
  with_items:
    - regexp: ^external_url
      line:   "external_url 'http://localhost/gitlab'"

    - regexp: ^# nginx\['enable'\]
      line:   "nginx['enable'] = false"

    - regexp: ^# unicorn\['port'\]
      line:   "unicorn['port'] = {{ gitlab_port }}"

- name: Configure GitLab
  command: gitlab-ctl reconfigure

- name: Import default data
  command: env force=yes gitlab-rake gitlab:setup
