- name: Configure the web settings
  lineinfile: dest=/etc/gitlab/gitlab.rb
              backrefs=yes
              regexp={{ item.regexp }}
              line={{ item.line }}
  with_items:
    - regexp: ^external_url
      line:   "external_url 'http://{{ gitlab_fqdn }}/gitlab'"

    - regexp: ^# gitlab_rails\['time_zone'\]
      line:   "gitlab_rails['time_zone'] = '{{ timezone }}'"

    - regexp: ^# unicorn\['port'\]
      line:   "unicorn['port'] = {{ unicorn_port }}"

    - regexp: ^# nginx\['listen_port'\]
      line:   "nginx['listen_port'] = {{ gitlab_port }}"

    - regexp: ^# nginx\['listen_https'\]
      line:   "nginx['listen_https'] = false"
