- hosts: web-servers
  become: yes
  roles:
    - init
    - timezone
    - redmine
    - gitlab
    - jenkins
    - nginx
### Backup settings
#    - mount_cifs
#    - redmine_backup
#    - gitlab_backup
