- name: Install the necessary dependencies
  apt: pkg={{ item }} force=yes
  with_items:
    - postfix
  environment: "{{ proxy_env }}"

- name: Download Redmine
  get_url: url=http://www.redmine.org/releases/redmine-{{ redmine_version }}.tar.gz
           dest=/tmp/redmine-{{ redmine_version }}.tar.gz
           timeout=30
  environment: "{{ proxy_env }}"

- name: Extract the download file
  unarchive: copy=no
             src=/tmp/redmine-{{ redmine_version }}.tar.gz
             dest=/tmp

- name: Install Redmine
  shell: mv /tmp/redmine-{{ redmine_version }} {{ redmine_home }}
  args:
    creates: "{{ redmine_home }}"

- include: database.yml

- include: unicorn.yml

- name: Install dependent gems
  shell: bundle install --path vendor/bundle --without development test rmagick
  args:
    chdir: "{{ redmine_home }}"
  environment: "{{ proxy_env }}"

- name: Configure the logrotate settings
  template: src=logrotate.conf.j2
            dest=/etc/logrotate.d/redmine

- name: Initialize a secret token
  shell: bundle exec rake generate_secret_token
  args:
    chdir: "{{ redmine_home }}"

- name: Initialize the databse
  shell: bundle exec rake db:migrate
  args:
    chdir: "{{ redmine_home }}"
  environment:
    RAILS_ENV: production

- name: Initialize defualt data
  shell: bundle exec rake redmine:load_default_data
  args:
    chdir: "{{ redmine_home }}"
  environment:
    RAILS_ENV: production
    REDMINE_LANG: ja

- name: Create a startup script for Redmine
  template: src=init.sh.j2
            dest=/etc/init.d/redmine
            mode=0755

- include: email.yml

- name: Start Redmine
  service: name=redmine state=restarted enabled=yes
