- name: apt-key add
  shell: wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
  environment: "{{ proxy_env }}"

- name: Add the package URL to sources.list
  shell: sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'

- name: apt-get update
  apt: update_cache=yes
  environment: "{{ proxy_env }}"
  tags:
    - apt-update

- name: Install Jenkins
  apt: pkg=jenkins force=yes
  environment: "{{ proxy_env }}"

- name: Backup /etc/default/jenkins
  shell: cp /etc/default/jenkins /etc/default/jenkins.bk
  args:
    creates: /etc/default/jenkins.bk

- name: Configure Jenkins port and URL
  lineinfile: dest=/etc/default/jenkins
              backrefs=yes
              regexp={{ item.regexp }}
              line={{ item.line }}
  with_items:
    - regexp: ^HTTP_PORT=
      line:   "HTTP_PORT={{ jenkins_port }}"

    - regexp: ^JENKINS_ARGS=
      line:   "JENKINS_ARGS=\"--webroot=/var/cache/$NAME/war --httpPort=$HTTP_PORT --prefix=$PREFIX\""

- name: Start Jenkins
  service: name=jenkins state=restarted
